// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SqrtServiceClient is the client API for SqrtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SqrtServiceClient interface {
	Sqrt(ctx context.Context, in *SqrtRequest, opts ...grpc.CallOption) (*SqrtResponse, error)
}

type sqrtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqrtServiceClient(cc grpc.ClientConnInterface) SqrtServiceClient {
	return &sqrtServiceClient{cc}
}

func (c *sqrtServiceClient) Sqrt(ctx context.Context, in *SqrtRequest, opts ...grpc.CallOption) (*SqrtResponse, error) {
	out := new(SqrtResponse)
	err := c.cc.Invoke(ctx, "/errorhandle.SqrtService/Sqrt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqrtServiceServer is the server API for SqrtService service.
// All implementations must embed UnimplementedSqrtServiceServer
// for forward compatibility
type SqrtServiceServer interface {
	Sqrt(context.Context, *SqrtRequest) (*SqrtResponse, error)
	mustEmbedUnimplementedSqrtServiceServer()
}

// UnimplementedSqrtServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSqrtServiceServer struct {
}

func (UnimplementedSqrtServiceServer) Sqrt(context.Context, *SqrtRequest) (*SqrtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sqrt not implemented")
}
func (UnimplementedSqrtServiceServer) mustEmbedUnimplementedSqrtServiceServer() {}

// UnsafeSqrtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqrtServiceServer will
// result in compilation errors.
type UnsafeSqrtServiceServer interface {
	mustEmbedUnimplementedSqrtServiceServer()
}

func RegisterSqrtServiceServer(s grpc.ServiceRegistrar, srv SqrtServiceServer) {
	s.RegisterService(&SqrtService_ServiceDesc, srv)
}

func _SqrtService_Sqrt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqrtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqrtServiceServer).Sqrt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/errorhandle.SqrtService/Sqrt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqrtServiceServer).Sqrt(ctx, req.(*SqrtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqrtService_ServiceDesc is the grpc.ServiceDesc for SqrtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqrtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "errorhandle.SqrtService",
	HandlerType: (*SqrtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sqrt",
			Handler:    _SqrtService_Sqrt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "errorhandle.proto",
}
